# Generated by Django 5.1.3 on 2025-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_options_alter_blog_date_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
