# Generated by Django 5.1.4 on 2025-08-03 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_comment_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(choices=[('new-website', 'New Website'), ('redesign', 'Website Redesign'), ('ecommerce', 'E-commerce Store'), ('maintenance', 'Website Maintenance'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('under-100k', 'Under ₦100,000'), ('100k-300k', '₦100,000 - ₦300,000'), ('300k-500k', '₦300,000 - ₦500,000'), ('500k-1m', '₦500,000 - ₦1,000,000'), ('over-1m', 'Over ₦1,000,000'), ('not-sure', 'Not sure yet')], max_length=20)),
                ('timeline', models.CharField(blank=True, max_length=50)),
                ('project_description', models.TextField(blank=True)),
                ('current_website', models.URLField(blank=True)),
                ('inspiration', models.TextField(blank=True)),
                ('consultation_type', models.CharField(choices=[('video-call', 'Video Call'), ('phone-call', 'Phone Call'), ('in-person', 'In-Person Meeting'), ('whatsapp', 'WhatsApp Consultation')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=20)),
                ('additional_services', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
