# Generated by Django 5.1.4 on 2025-09-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_coursereview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
