# Generated by Django 5.1.4 on 2025-09-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_coursereview_helpful_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to make all lectures in this section inaccessible (show padlock)'),
        ),
    ]
