# Generated by Django 5.1.4 on 2025-09-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_paymentmethod_alter_courseenrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='payment_method',
            field=models.CharField(choices=[('kora_pay', 'Kora Pay'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('pay_with_bank', 'Pay with Bank'), ('mobile_money', 'Mobile Money')], max_length=20),
        ),
    ]
