# Generated by Django 5.1.4 on 2025-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_coursepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp contact link for enrolled students'),
        ),
    ]
