# Generated by Django 5.1.4 on 2025-09-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_instructor_whatsapp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='consultation_cost',
            field=models.CharField(blank=True, help_text='Cost in Naira', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='session_duration',
            field=models.CharField(blank=True, help_text='Duration in minutes (20, 40, or 60)', max_length=10),
        ),
    ]
