# Generated by Django 5.1.4 on 2025-09-30 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_consultationbooking_consultation_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_method', models.CharField(choices=[('kora_pay', 'Kora Pay'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('pay_with_bank', 'Pay with Bank'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('consultation_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.consultationbooking')),
            ],
            options={
                'verbose_name': 'Consultation Payment',
                'verbose_name_plural': 'Consultation Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
