# Generated by Django 5.1.4 on 2025-09-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_consultationpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
