# Generated by Django 5.2.7 on 2025-11-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_workshopregistration_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='pin',
            field=models.CharField(blank=True, help_text='Unique PIN for participant', max_length=20, null=True),
        ),
    ]
