# Generated by Django 5.2.7 on 2025-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_workshopregistration_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
