# Generated by Django 5.2.7 on 2025-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_workshopregistration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccessPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='PIN code for early access', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description (e.g., VIP, Beta Tester)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to revoke access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this PIN has been used')),
            ],
            options={
                'verbose_name': 'Course Access PIN',
                'verbose_name_plural': 'Course Access PINs',
                'ordering': ['-created_at'],
            },
        ),
    ]
