# Generated by Django 5.2.7 on 2025-11-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_courseaccesspin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseaccesspin',
            name='description',
        ),
    ]
